name: gdl
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - torchinfo
  - torchmetrics
  - ipykernel
  - scipy
  - scikit-learn
  - seaborn
  - pandas
  - geopandas
  - shapely
  - gdal
  - pdal
  - python-pdal
  - rasterio
  - rioxarray
  - rio-tiler
  - trimesh
  - pymeshlab
  - pyvista
  - plyfile
  - pyyaml
  - pycocotools
  - tensorboard
  - pip
  - pip:
      - torch-geometric
      - torch-scatter
      - torch-sparse
      - torch-cluster
      - torch-spline-conv
      - startinpy
      - fast-simplification
      - "git+https://github.com/facebookresearch/pytorch3d.git"
