# dataset
dataset: sum
load_feature: all
batch: 1
workers: 9

# train config
epoch: 200
patience: 200
lr: 0.005
w_decay: 0.0001
device: cuda

# model
model: LGAP
num_convs: 4
pool_factors: 
  - 3
  - 3
  - 3
  - 3
num_block: 1
alpha: 0.001
beta: 0.01

in_channels: 18
hid_channels: 30
out_channels: 7

# save
path: save/sum/sum_lgap_feature