# dataset
dataset: bbw
load_feature: all
in_features_dim: 4
batch: 1
workers: 9

# train config
epoch: 100
patience: 100
lr: 0.01
w_decay: 0.0001
device: cuda

# model
in_channels: 18
out_channels: 1

# save
path: save/bbw/bbw_kpconv_feature