# dataset
dataset: bbw
load_feature: all
batch: 4
workers: 8

# train config
epoch: 100
patience: 100
lr: 0.01
w_decay: 0.0001
device: cuda

# model
in_channels: 9
out_channels: 1
decimation: 4
num_nbrs: 16

# save
path: save/bbw/bbw_randlanet_feature