# dataset
dataset: bbw
load_feature: all
batch: 4
workers: 8

# train config
epoch: 100
patience: 100
lr: 0.01
w_decay: 0.0001
device: cuda

# model
in_channels: 9
out_channels: 1
hid_channels: 128
num_layers: 28

# save
path: save/bbw/bbw_deepergcn_feature