# dataset
dataset: bbw
load_feature: all
batch: 4
workers: 9

# train config
epoch: 100
patience: 100
lr: 0.01
w_decay: 0.0001
device: cuda

# model
num_convs: 4
pool_factors: 
  - 3
  - 3
  - 3
  - 3
num_nbrs: 16
num_block: 1
alpha: 0.001
beta: 0.01

in_channels: 18
hid_channels: 30
out_channels: 1

# save
path: save/bbw/bbw_lmseg_feature