# dataset
dataset: bbw
load_feature: all
batch: 4
workers: 8
num_points: 18000

# train config
epoch: 100
patience: 100
lr: 0.01
w_decay: 0.0001
device: cuda

# model
in_channels: 10
out_channels: 1

# save
path: save/bbw/bbw_kpconv_feature