# dataset
dataset: bbw
batch: 8
workers: 8

# train config
epoch: 100
patience: 100
lr: 0.001
w_decay: 0.0001
device: cuda

# model
in_channels: 27
out_channels: 1
hid_channels: 128
num_layers: 28

# save
path: save/bbw/deepergcn_feature