# dataset
dataset: bbw
batch: 8
workers: 8

# train config
epoch: 100
patience: 100
lr: 0.001
w_decay: 0.0001
device: cuda

# model
in_channels: 27
hid_channels: 256
out_channels: 1
depth: 4
pool_ratios:
  - 0.9
  - 0.7
  - 0.6
  - 0.5
sum_res: False
act: 'relu'

# save
path: save/bbw/gunet_feature