# dataset
dataset: bbw
load_feature: all
batch: 8
workers: 8

# train config
epoch: 100
patience: 100
lr: 0.001
w_decay: 0.0001
device: cuda

# model
num_convs: 3
pool_factors: 
  - 3
  - 3
  - 3
num_nbrs: 8
num_block: 1
alpha: 0.001
beta: 0.01

in_channels: 3
hid_channels: 72
out_channels: 1

# save
path: save/bbw/lmseg_feature_nbrs_8