# dataset
dataset: bbw
load_feature: all
batch: 8
workers: 8

# train config
epoch: 100
patience: 100
lr: 0.01
w_decay: 0.0001
device: cuda

# model
in_channels: 27
out_channels: 1
pool_ratio: 0.25
num_nbrs: 3

# save
path: save/bbw/pointnet2_feature