# dataset
dataset: h3d
batch: 1
workers: 8

# train config
epoch: 200
patience: 200
lr: 0.001
w_decay: 0.0001
device: cuda

# model
model: HGAP
num_convs: 3
pool_factors: 
  - 3
  - 3
  - 3
num_nbrs: 20
num_block: 1
alpha: 0.001
beta: 0.01

in_channels: 3
hid_channels: 72
out_channels: 12

# save
path: save/h3d/hgap_feature